openapi: '3.0.3'
info:
  title: API Title
  version: '1.0'
servers:
  - url: https://api.server.test/v1
paths:
  /api/v1/promozioni:
    get:
      responses:
        '200':
          description: A JSON array of promotions
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    data:
                      type: string
                      format: date-time
                    titolo:
                      type: string
                    promotore:
                      type: string
                    descrizione:
                      type: string
                    immagine:
                      type: string
                      format: uri
                    tipoAnnuncio:
                      type: string
        '500':
          description: Internal Server Error
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                data:
                  type: string
                  format: date-time
                titolo:
                  type: string
                promotore:
                  type: string
                descrizione:
                  type: string
                immagine:
                  type: string
                  format: uri
                tipoAnnuncio:
                  type: string
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /api/v1/carrello/clientId:
    get:
      responses:
        '200':
          description: A JSON con il carrello dei prodotti
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    nome:
                      type: string
                    descrizione:
                      type: string
                    venditore:
                      type: string
                    quantita:
                      type: number  
                    costo:
                      type: number    
                    tag:
                      type: string
                    immagine:
                      type: string
                      format: uri
        '500':
          description: Internal Server Error
  /api/v1/carrello/clientId/add:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                descrizione:
                  type: string
                venditore:
                  type: string
                quantita:
                  type: number  
                costo:
                  type: number    
                tag:
                  type: string
                immagine:
                  type: string
                  format: uri
      responses:
        '200':
          description: Created
        '400':
          description: Quantità totale nel carrello eccede la quantità disponibile
        '404':
          description: Prodotto non trovato
        '500':
          description: Internal Server Error
  /api/v1/carrello/clientId/removeOne:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                descrizione:
                  type: string
                venditore:
                  type: string
                quantita:
                  type: number  
                costo:
                  type: number    
                tag:
                  type: string
                immagine:
                  type: string
                  format: uri
      responses:
        '200':
          description: Removed
        '404':
          description: Cliente non trovato
        '500':
          description: Internal Server Error
  /api/v1/prodotto/venditore/:id:
    get:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                nome:
                  type: string
                descrizione:
                  type: string
                venditore:
                  type: string
                quantita:
                  type: number  
                costo:
                  type: number    
                tag:
                  type: string
                immagine:
                  type: string
                  format: uri
      responses:
        '200':
          description: A JSON array of products
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    nome:
                      type: string
                    descrizione:
                      type: string
                    venditore:
                      type: string
                    quantita:
                      type: number  
                    costo:
                      type: number    
                    tag:
                      type: string
                    immagine:
                      type: string
                      format: uri
        '404':
          description: Prodotto non trovato
        '500':
          description: Internal Server Error  
  /api/v1/venditore: 
    get:
      responses:
        '200':
          description: A JSON array of sellers
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    nome:
                      type: string
                    cognome:
                      type: string
                    birthdate:
                      type: string
                      format: date-time
                    email:
                      type: string
                      format: email
                    username:
                      type: string    
                    password:
                      type: string
                    sede:
                      type: string
                    descrizione:
                      type: string
                    tipo:
                      type: string
                    datiPagamento:
                      type: string
        '500':
          description: Internal Server Error
  /api/v1/venditore/:id:
    get:
      responses:
        '200':
          description: A JSON with one seller
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  nome:
                    type: string
                  cognome:
                    type: string
                  birthdate:
                    type: string
                    format: date-time
                  email:
                    type: string
                    format: email
                  username:
                    type: string    
                  password:
                    type: string
                  sede:
                    type: string
                  descrizione:
                    type: string
                  tipo:
                    type: string
                  datiPagamento:
                    type: string
        '404':
          description: Venditore non trovato
        '500':
          description: Internal Server Error
  /api/v1/prodotto: 
    post: 
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                descrizione:
                  type: string
                venditore:
                  type: string
                quantita:
                  type: number  
                costo:
                  type: number    
                tag:
                  type: string
                immagine:
                  type: string
                  format: uri
      responses:
        '201':
          description: Created
        '500':
          description: Internal Server Error
  /api/v1/prodotto/:id: 
    delete: 
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                nome:
                  type: string
                descrizione:
                  type: string
                venditore:
                  type: string
                quantita:
                  type: number  
                costo:
                  type: number    
                tag:
                  type: string
                immagine:
                  type: string
                  format: uri
      responses:
        '200':
          description: Prodotto eliminato
        '500':
          description: Internal Server Error


