openapi: '3.0.3'
info:
  title: API MarkeTrento
  version: '1.0'
servers:
  - url: https://api.server.test/v1
paths:
  /:
    get:
      summary: Default page
      description: Returns the default page of the API.
      responses:
        '200':
          description: Home page
          content:
            html:
              schema:
                type: string
  /mercato:
    get:
      summary: Market page
      description: Returns the market page of the API.
      responses:
        '200':
          description: Market page
          content:
            html:
              schema:
                type: string
  /login:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful
          content:
            html:
              schema:
                type: string
        '401':
          description: Unauthorized
          content:
            html:
              schema:
                type: string
  /loginbusiness:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: email
                password:
                  type: string
      responses:
        '200':
          description: Login successful
          content:
            html:
              schema:
                type: string
        '401':
          description: Unauthorized
          content:
            html:
              schema:
                type: string
  /api/v1/promozioni:
    get:
      responses:
        '200':
          description: A JSON array of promotions
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    data:
                      type: string
                      description: date-time
                    titolo:
                      type: string
                    promotore:
                      type: string
                    descrizione:
                      type: string
                    immagine:
                      type: string
                      description: uri
                    tipoAnnuncio:
                      type: string
        '500':
          description: Internal Server Error
    post:
      requestBody:
        content:
          application/FormData:
            schema:
              type: object
              properties:
                id:
                  type: integer
                data:
                  type: string
                  description: date-time
                titolo:
                  type: string
                promotore:
                  type: string
                descrizione:
                  type: string
                immagine:
                  type: object
                  properties:
                    file:
                      type: string
                      format: binary
                tipoAnnuncio:
                  type: string
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /api/v1/carrello/clientId:
    get:
      responses:
        '200':
          description: A JSON con il carrello dei prodotti
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    nome:
                      type: string
                    descrizione:
                      type: string
                    venditore:
                      type: string
                    quantita:
                      type: number  
                    costo:
                      type: number    
                    tag:
                      type: string
                    immagine:
                      type: string
                      description: uri
        '500':
          description: Internal Server Error
  /api/v1/carrello/clientId/add:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                descrizione:
                  type: string
                venditore:
                  type: string
                quantita:
                  type: number  
                costo:
                  type: number    
                tag:
                  type: string
                immagine:
                  type: string
                  description: uri
      responses:
        '200':
          description: Created
        '400':
          description: Quantità totale nel carrello eccede la quantità disponibile
        '404':
          description: Prodotto non trovato
        '500':
          description: Internal Server Error
  /api/v1/carrelli/clientId/removeOne:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                descrizione:
                  type: string
                venditore:
                  type: string
                quantita:
                  type: number  
                costo:
                  type: number    
                tag:
                  type: string
                immagine:
                  type: string
                  description: uri
      responses:
        '200':
          description: Removed
        '404':
          description: Cliente non trovato
        '500':
          description: Internal Server Error
  /api/v1/prodotti/venditore/:id:
    get:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                nome:
                  type: string
                descrizione:
                  type: string
                venditore:
                  type: string
                quantita:
                  type: number  
                costo:
                  type: number    
                tag:
                  type: string
                immagine:
                  type: string
                  description: uri
      responses:
        '200':
          description: A JSON array of products
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    nome:
                      type: string
                    descrizione:
                      type: string
                    venditore:
                      type: string
                    quantita:
                      type: number  
                    costo:
                      type: number    
                    tag:
                      type: string
                    immagine:
                      type: string
                      description: uri
        '404':
          description: Prodotto non trovato
        '500':
          description: Internal Server Error  
  /api/v1/venditori: 
    get:
      responses:
        '200':
          description: A JSON array of sellers
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    nome:
                      type: string
                    cognome:
                      type: string
                    birthdate:
                      type: string
                      description: date-time
                    email:
                      type: string
                      description: email
                    username:
                      type: string    
                    password:
                      type: string
                    sede:
                      type: string
                    descrizione:
                      type: string
                    tipo:
                      type: string
                    datiPagamento:
                      type: string
        '500':
          description: Internal Server Error
  /api/v1/venditori/:id:
    get:
      responses:
        '200':
          description: A JSON with one seller
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  nome:
                    type: string
                  cognome:
                    type: string
                  birthdate:
                    type: string
                    description: date-time
                  email:
                    type: string
                    description: email
                  username:
                    type: string    
                  password:
                    type: string
                  sede:
                    type: string
                  descrizione:
                    type: string
                  tipo:
                    type: string
                  datiPagamento:
                    type: string
        '404':
          description: Venditore non trovato
        '500':
          description: Internal Server Error
  /api/v1/prodotti: 
    post: 
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                descrizione:
                  type: string
                venditore:
                  type: string
                quantita:
                  type: number  
                costo:
                  type: number    
                tag:
                  type: string
                immagine:
                  type: string
                  description: uri
      responses:
        '201':
          description: Created
        '500':
          description: Internal Server Error
  /api/v1/prodotti/:id:
    get:
      responses:
        '200':
          description: A JSON with one product
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  nome:
                    type: string
                  descrizione:
                    type: string
                  venditore:
                    type: string
                  quantita:
                    type: number  
                  costo:
                    type: number    
                  tag:
                    type: string
                  immagine:
                    type: string
                    description: uri
        '404':
          description: prodotto non trovato
        '500':
          description: Internal Server Error
    put: 
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                nome:
                  type: string
                descrizione:
                  type: string
                venditore:
                  type: string
                quantita:
                  type: number  
                costo:
                  type: number    
                tag:
                  type: string
                immagine:
                  type: string
                  description: uri
      responses:
        '200':
          description: Prodotto aggiornato
        '500':
          description: Internal Server Error
    delete: 
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                nome:
                  type: string
                descrizione:
                  type: string
                venditore:
                  type: string
                quantita:
                  type: number  
                costo:
                  type: number    
                tag:
                  type: string
                immagine:
                  type: string
                  description: uri
      responses:
        '200':
          description: Prodotto eliminato
        '500':
          description: Internal Server Error
  /api/v1/tags:
    get:
      responses:
        '200':
          description: A JSON array of tags
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    nome:
                      type: string
        '500':
          description: Internal Server Error
  /api/v1/tags/:id:
    get:
      responses:
        '200':
          description: A JSON with one tag
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  nome:
                    type: string
        '404':
          description: Tag non trovata
        '500':
          description: Internal Server Error
    put:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                nome:
                  type: string
      responses:
        '200':
          description: Tag aggiornata
        '500':
          description: Internal Server Error
    delete:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                nome:
                  type: string
      responses:
        '200':
          description: Tag eliminata
        '500':
          description: Internal Server Error